/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif

// Avoid multiple includes of RNMapsforgeVtmExtPathColorRampSpec symbols
#ifndef RNMapsforgeVtmExtPathColorRampSpec_H
#define RNMapsforgeVtmExtPathColorRampSpec_H

#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>


NS_ASSUME_NONNULL_BEGIN
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct GeometryStyle {
      std::optional<double> strokeWidth() const;
      NSString *strokeColor() const;
      NSString *fillColor() const;
      std::optional<double> fillAlpha() const;
      std::optional<double> buffer() const;
      std::optional<double> scalingZoomLevel() const;
      NSString *cap() const;
      std::optional<bool> fixed() const;
      std::optional<double> strokeIncrease() const;
      std::optional<double> blur() const;
      std::optional<double> stipple() const;
      NSString *stippleColor() const;
      std::optional<double> stippleWidth() const;
      std::optional<double> dropDistance() const;
      std::optional<bool> textureRepeat() const;
      std::optional<double> heightOffset() const;
      std::optional<bool> randomOffset() const;
      std::optional<bool> transparent() const;

      GeometryStyle(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeLayerPathColorRamp_GeometryStyle)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_GeometryStyle:(id)json;
@end
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct CreateLayerParams {
      std::optional<double> nativeNodeHandle() const;
      std::optional<double> positionIndex() const;
      std::optional<facebook::react::LazyVector<facebook::react::LazyVector<double>>> coordinates() const;
      std::optional<facebook::react::LazyVector<double>> segmentValues() const;
      std::optional<facebook::react::LazyVector<NSString *>> colorRampStops() const;
      std::optional<bool> supportsGestures() const;
      std::optional<JS::NativeLayerPathColorRamp::GeometryStyle> style() const;

      CreateLayerParams(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeLayerPathColorRamp_CreateLayerParams)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_CreateLayerParams:(id)json;
@end
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct RemoveLayerParams {
      double nativeNodeHandle() const;
      NSString *uuid() const;

      RemoveLayerParams(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeLayerPathColorRamp_RemoveLayerParams)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_RemoveLayerParams:(id)json;
@end
@protocol NativeLayerPathColorRampSpec <RCTBridgeModule, RCTTurboModule>

- (void)createLayer:(JS::NativeLayerPathColorRamp::CreateLayerParams &)params
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)removeLayer:(JS::NativeLayerPathColorRamp::RemoveLayerParams &)params
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end

@interface NativeLayerPathColorRampSpecBase : NSObject {
@protected
facebook::react::EventEmitterCallback _eventEmitterCallback;
}
- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper;


@end

namespace facebook::react {
  /**
   * ObjC++ class for module 'NativeLayerPathColorRamp'
   */
  class JSI_EXPORT NativeLayerPathColorRampSpecJSI : public ObjCTurboModule {
  public:
    NativeLayerPathColorRampSpecJSI(const ObjCTurboModule::InitParams &params);
  };
} // namespace facebook::react
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::strokeWidth() const
{
  id const p = _v[@"strokeWidth"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::strokeColor() const
{
  id const p = _v[@"strokeColor"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::fillColor() const
{
  id const p = _v[@"fillColor"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::fillAlpha() const
{
  id const p = _v[@"fillAlpha"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::buffer() const
{
  id const p = _v[@"buffer"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::scalingZoomLevel() const
{
  id const p = _v[@"scalingZoomLevel"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::cap() const
{
  id const p = _v[@"cap"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::fixed() const
{
  id const p = _v[@"fixed"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::strokeIncrease() const
{
  id const p = _v[@"strokeIncrease"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::blur() const
{
  id const p = _v[@"blur"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::stipple() const
{
  id const p = _v[@"stipple"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::stippleColor() const
{
  id const p = _v[@"stippleColor"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::stippleWidth() const
{
  id const p = _v[@"stippleWidth"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::dropDistance() const
{
  id const p = _v[@"dropDistance"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::textureRepeat() const
{
  id const p = _v[@"textureRepeat"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::heightOffset() const
{
  id const p = _v[@"heightOffset"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::randomOffset() const
{
  id const p = _v[@"randomOffset"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::transparent() const
{
  id const p = _v[@"transparent"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::CreateLayerParams::nativeNodeHandle() const
{
  id const p = _v[@"nativeNodeHandle"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::CreateLayerParams::positionIndex() const
{
  id const p = _v[@"positionIndex"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<facebook::react::LazyVector<facebook::react::LazyVector<double>>> JS::NativeLayerPathColorRamp::CreateLayerParams::coordinates() const
{
  id const p = _v[@"coordinates"];
  return RCTBridgingToOptionalVec(p, ^facebook::react::LazyVector<double>(id itemValue_0) { return RCTBridgingToVec(itemValue_0, ^double(id itemValue_1) { return RCTBridgingToDouble(itemValue_1); }); });
}
inline std::optional<facebook::react::LazyVector<double>> JS::NativeLayerPathColorRamp::CreateLayerParams::segmentValues() const
{
  id const p = _v[@"segmentValues"];
  return RCTBridgingToOptionalVec(p, ^double(id itemValue_0) { return RCTBridgingToDouble(itemValue_0); });
}
inline std::optional<facebook::react::LazyVector<NSString *>> JS::NativeLayerPathColorRamp::CreateLayerParams::colorRampStops() const
{
  id const p = _v[@"colorRampStops"];
  return RCTBridgingToOptionalVec(p, ^NSString *(id itemValue_0) { return RCTBridgingToString(itemValue_0); });
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::CreateLayerParams::supportsGestures() const
{
  id const p = _v[@"supportsGestures"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<JS::NativeLayerPathColorRamp::GeometryStyle> JS::NativeLayerPathColorRamp::CreateLayerParams::style() const
{
  id const p = _v[@"style"];
  return (p == nil ? std::nullopt : std::make_optional(JS::NativeLayerPathColorRamp::GeometryStyle(p)));
}
inline double JS::NativeLayerPathColorRamp::RemoveLayerParams::nativeNodeHandle() const
{
  id const p = _v[@"nativeNodeHandle"];
  return RCTBridgingToDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::RemoveLayerParams::uuid() const
{
  id const p = _v[@"uuid"];
  return RCTBridgingToString(p);
}
NS_ASSUME_NONNULL_END
#endif // RNMapsforgeVtmExtPathColorRampSpec_H
