/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif

// Avoid multiple includes of RNMapsforgeVtmExtPathColorRampSpec symbols
#ifndef RNMapsforgeVtmExtPathColorRampSpec_H
#define RNMapsforgeVtmExtPathColorRampSpec_H

#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>


NS_ASSUME_NONNULL_BEGIN
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct GeometryStyle {
      std::optional<double> strokeWidth() const;
      NSString *strokeColor() const;
      NSString *fillColor() const;
      std::optional<double> fillAlpha() const;
      std::optional<double> buffer() const;
      std::optional<double> scalingZoomLevel() const;
      NSString *cap() const;
      std::optional<bool> fixed() const;
      std::optional<double> strokeIncrease() const;
      std::optional<double> blur() const;
      std::optional<double> stipple() const;
      NSString *stippleColor() const;
      std::optional<double> stippleWidth() const;
      std::optional<double> dropDistance() const;
      std::optional<bool> textureRepeat() const;
      std::optional<double> heightOffset() const;
      std::optional<bool> randomOffset() const;
      std::optional<bool> transparent() const;

      GeometryStyle(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeLayerPathColorRamp_GeometryStyle)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_GeometryStyle:(id)json;
@end
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct CreateLayerParams {
      std::optional<double> nativeNodeHandle() const;
      std::optional<double> positionIndex() const;
      std::optional<facebook::react::LazyVector<facebook::react::LazyVector<double>>> coordinates() const;
      NSString *fragmentUuid() const;
      std::optional<facebook::react::LazyVector<double>> segmentValues() const;
      std::optional<facebook::react::LazyVector<double>> vertexValues() const;
      std::optional<facebook::react::LazyVector<NSString *>> colorRampStops() const;
      std::optional<double> blendRatio() const;
      std::optional<bool> supportsGestures() const;
      std::optional<JS::NativeLayerPathColorRamp::GeometryStyle> style() const;

      CreateLayerParams(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeLayerPathColorRamp_CreateLayerParams)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_CreateLayerParams:(id)json;
@end
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct RemoveLayerParams {
      double nativeNodeHandle() const;
      NSString *uuid() const;

      RemoveLayerParams(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeLayerPathColorRamp_RemoveLayerParams)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_RemoveLayerParams:(id)json;
@end
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct ConstantsStyle {

      struct Builder {
        // Backwards compat for RCTTypedModuleConstants
        using ResultT = ConstantsStyle;

        struct Input {
          std::optional<double> strokeWidth;
          NSString *strokeColor;
          NSString *cap;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing ConstantsStyle */
        Builder(ConstantsStyle i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static ConstantsStyle fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      ConstantsStyle(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct ConstantsResponseInclude {

      struct Builder {
        // Backwards compat for RCTTypedModuleConstants
        using ResultT = ConstantsResponseInclude;

        struct Input {
          std::optional<double> coordinates;
          std::optional<double> bounds;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing ConstantsResponseInclude */
        Builder(ConstantsResponseInclude i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static ConstantsResponseInclude fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      ConstantsResponseInclude(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
namespace JS {
  namespace NativeLayerPathColorRamp {
    struct Constants {

      struct Builder {
        // Backwards compat for RCTTypedModuleConstants
        using ResultT = Constants;

        struct Input {
          std::optional<JS::NativeLayerPathColorRamp::ConstantsStyle::Builder> style;
          std::optional<JS::NativeLayerPathColorRamp::ConstantsResponseInclude::Builder> responseInclude;
          std::optional<double> gestureScreenDistance;
          std::optional<double> simplificationTolerance;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol NativeLayerPathColorRampSpec <RCTBridgeModule, RCTTurboModule>

- (void)createLayer:(JS::NativeLayerPathColorRamp::CreateLayerParams &)params
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)removeLayer:(JS::NativeLayerPathColorRamp::RemoveLayerParams &)params
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;
- (facebook::react::ModuleConstants<JS::NativeLayerPathColorRamp::Constants>)constantsToExport;
- (facebook::react::ModuleConstants<JS::NativeLayerPathColorRamp::Constants>)getConstants;

@end

@interface NativeLayerPathColorRampSpecBase : NSObject {
@protected
facebook::react::EventEmitterCallback _eventEmitterCallback;
}
- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper;


@end

namespace facebook::react {
  /**
   * ObjC++ class for module 'NativeLayerPathColorRamp'
   */
  class JSI_EXPORT NativeLayerPathColorRampSpecJSI : public ObjCTurboModule {
  public:
    NativeLayerPathColorRampSpecJSI(const ObjCTurboModule::InitParams &params);
  };
} // namespace facebook::react
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::strokeWidth() const
{
  id const p = _v[@"strokeWidth"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::strokeColor() const
{
  id const p = _v[@"strokeColor"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::fillColor() const
{
  id const p = _v[@"fillColor"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::fillAlpha() const
{
  id const p = _v[@"fillAlpha"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::buffer() const
{
  id const p = _v[@"buffer"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::scalingZoomLevel() const
{
  id const p = _v[@"scalingZoomLevel"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::cap() const
{
  id const p = _v[@"cap"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::fixed() const
{
  id const p = _v[@"fixed"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::strokeIncrease() const
{
  id const p = _v[@"strokeIncrease"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::blur() const
{
  id const p = _v[@"blur"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::stipple() const
{
  id const p = _v[@"stipple"];
  return RCTBridgingToOptionalDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::GeometryStyle::stippleColor() const
{
  id const p = _v[@"stippleColor"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::stippleWidth() const
{
  id const p = _v[@"stippleWidth"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::dropDistance() const
{
  id const p = _v[@"dropDistance"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::textureRepeat() const
{
  id const p = _v[@"textureRepeat"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::GeometryStyle::heightOffset() const
{
  id const p = _v[@"heightOffset"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::randomOffset() const
{
  id const p = _v[@"randomOffset"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::GeometryStyle::transparent() const
{
  id const p = _v[@"transparent"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::CreateLayerParams::nativeNodeHandle() const
{
  id const p = _v[@"nativeNodeHandle"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeLayerPathColorRamp::CreateLayerParams::positionIndex() const
{
  id const p = _v[@"positionIndex"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<facebook::react::LazyVector<facebook::react::LazyVector<double>>> JS::NativeLayerPathColorRamp::CreateLayerParams::coordinates() const
{
  id const p = _v[@"coordinates"];
  return RCTBridgingToOptionalVec(p, ^facebook::react::LazyVector<double>(id itemValue_0) { return RCTBridgingToVec(itemValue_0, ^double(id itemValue_1) { return RCTBridgingToDouble(itemValue_1); }); });
}
inline NSString *JS::NativeLayerPathColorRamp::CreateLayerParams::fragmentUuid() const
{
  id const p = _v[@"fragmentUuid"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<facebook::react::LazyVector<double>> JS::NativeLayerPathColorRamp::CreateLayerParams::segmentValues() const
{
  id const p = _v[@"segmentValues"];
  return RCTBridgingToOptionalVec(p, ^double(id itemValue_0) { return RCTBridgingToDouble(itemValue_0); });
}
inline std::optional<facebook::react::LazyVector<double>> JS::NativeLayerPathColorRamp::CreateLayerParams::vertexValues() const
{
  id const p = _v[@"vertexValues"];
  return RCTBridgingToOptionalVec(p, ^double(id itemValue_0) { return RCTBridgingToDouble(itemValue_0); });
}
inline std::optional<facebook::react::LazyVector<NSString *>> JS::NativeLayerPathColorRamp::CreateLayerParams::colorRampStops() const
{
  id const p = _v[@"colorRampStops"];
  return RCTBridgingToOptionalVec(p, ^NSString *(id itemValue_0) { return RCTBridgingToString(itemValue_0); });
}
inline std::optional<double> JS::NativeLayerPathColorRamp::CreateLayerParams::blendRatio() const
{
  id const p = _v[@"blendRatio"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeLayerPathColorRamp::CreateLayerParams::supportsGestures() const
{
  id const p = _v[@"supportsGestures"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<JS::NativeLayerPathColorRamp::GeometryStyle> JS::NativeLayerPathColorRamp::CreateLayerParams::style() const
{
  id const p = _v[@"style"];
  return (p == nil ? std::nullopt : std::make_optional(JS::NativeLayerPathColorRamp::GeometryStyle(p)));
}
inline double JS::NativeLayerPathColorRamp::RemoveLayerParams::nativeNodeHandle() const
{
  id const p = _v[@"nativeNodeHandle"];
  return RCTBridgingToDouble(p);
}
inline NSString *JS::NativeLayerPathColorRamp::RemoveLayerParams::uuid() const
{
  id const p = _v[@"uuid"];
  return RCTBridgingToString(p);
}
inline JS::NativeLayerPathColorRamp::ConstantsStyle::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto strokeWidth = i.strokeWidth;
  d[@"strokeWidth"] = strokeWidth.has_value() ? @((double)strokeWidth.value()) : nil;
  auto strokeColor = i.strokeColor;
  d[@"strokeColor"] = strokeColor;
  auto cap = i.cap;
  d[@"cap"] = cap;
  return d;
}) {}
inline JS::NativeLayerPathColorRamp::ConstantsStyle::Builder::Builder(ConstantsStyle i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline JS::NativeLayerPathColorRamp::ConstantsResponseInclude::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto coordinates = i.coordinates;
  d[@"coordinates"] = coordinates.has_value() ? @((double)coordinates.value()) : nil;
  auto bounds = i.bounds;
  d[@"bounds"] = bounds.has_value() ? @((double)bounds.value()) : nil;
  return d;
}) {}
inline JS::NativeLayerPathColorRamp::ConstantsResponseInclude::Builder::Builder(ConstantsResponseInclude i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline JS::NativeLayerPathColorRamp::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto style = i.style;
  d[@"style"] = style.has_value() ? style.value().buildUnsafeRawValue() : nil;
  auto responseInclude = i.responseInclude;
  d[@"responseInclude"] = responseInclude.has_value() ? responseInclude.value().buildUnsafeRawValue() : nil;
  auto gestureScreenDistance = i.gestureScreenDistance;
  d[@"gestureScreenDistance"] = gestureScreenDistance.has_value() ? @((double)gestureScreenDistance.value()) : nil;
  auto simplificationTolerance = i.simplificationTolerance;
  d[@"simplificationTolerance"] = simplificationTolerance.has_value() ? @((double)simplificationTolerance.value()) : nil;
  return d;
}) {}
inline JS::NativeLayerPathColorRamp::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}
NS_ASSUME_NONNULL_END
#endif // RNMapsforgeVtmExtPathColorRampSpec_H
