/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "RNMapsforgeVtmExtPathColorRampSpec.h"


@implementation NativeLayerPathColorRampSpecBase


- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper
{
  _eventEmitterCallback = std::move(eventEmitterCallbackWrapper->_eventEmitterCallback);
}
@end

@implementation RCTCxxConvert (NativeLayerPathColorRamp_GeometryStyle)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_GeometryStyle:(id)json
{
  return facebook::react::managedPointer<JS::NativeLayerPathColorRamp::GeometryStyle>(json);
}
@end
@implementation RCTCxxConvert (NativeLayerPathColorRamp_CreateLayerParams)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_CreateLayerParams:(id)json
{
  return facebook::react::managedPointer<JS::NativeLayerPathColorRamp::CreateLayerParams>(json);
}
@end
@implementation RCTCxxConvert (NativeLayerPathColorRamp_RemoveLayerParams)
+ (RCTManagedPointer *)JS_NativeLayerPathColorRamp_RemoveLayerParams:(id)json
{
  return facebook::react::managedPointer<JS::NativeLayerPathColorRamp::RemoveLayerParams>(json);
}
@end
namespace facebook::react {
  
    static facebook::jsi::Value __hostFunction_NativeLayerPathColorRampSpecJSI_createLayer(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "createLayer", @selector(createLayer:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeLayerPathColorRampSpecJSI_removeLayer(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "removeLayer", @selector(removeLayer:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeLayerPathColorRampSpecJSI_addListener(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "addListener", @selector(addListener:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeLayerPathColorRampSpecJSI_removeListeners(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "removeListeners", @selector(removeListeners:), args, count);
    }

  NativeLayerPathColorRampSpecJSI::NativeLayerPathColorRampSpecJSI(const ObjCTurboModule::InitParams &params)
    : ObjCTurboModule(params) {
      
        methodMap_["createLayer"] = MethodMetadata {1, __hostFunction_NativeLayerPathColorRampSpecJSI_createLayer};
        setMethodArgConversionSelector(@"createLayer", 0, @"JS_NativeLayerPathColorRamp_CreateLayerParams:");
        
        methodMap_["removeLayer"] = MethodMetadata {1, __hostFunction_NativeLayerPathColorRampSpecJSI_removeLayer};
        setMethodArgConversionSelector(@"removeLayer", 0, @"JS_NativeLayerPathColorRamp_RemoveLayerParams:");
        
        methodMap_["addListener"] = MethodMetadata {1, __hostFunction_NativeLayerPathColorRampSpecJSI_addListener};
        
        
        methodMap_["removeListeners"] = MethodMetadata {1, __hostFunction_NativeLayerPathColorRampSpecJSI_removeListeners};
        
  }
} // namespace facebook::react
