/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


#pragma mark - NativeLayerPathColorRampCreateLayerParams

template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6, typename P7, typename P8>
struct NativeLayerPathColorRampCreateLayerParams {
  P0 nativeNodeHandle{};
  P1 positionIndex{};
  P2 coordinates{};
  P3 fragmentUuid{};
  P4 segmentValues{};
  P5 colorRampStops{};
  P6 blendRatio{};
  P7 supportsGestures{};
  P8 style;
  bool operator==(const NativeLayerPathColorRampCreateLayerParams &other) const {
    return nativeNodeHandle == other.nativeNodeHandle && positionIndex == other.positionIndex && coordinates == other.coordinates && fragmentUuid == other.fragmentUuid && segmentValues == other.segmentValues && colorRampStops == other.colorRampStops && blendRatio == other.blendRatio && supportsGestures == other.supportsGestures && style == other.style;
  }
};

template <typename T>
struct NativeLayerPathColorRampCreateLayerParamsBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.nativeNodeHandle)>(rt, value.getProperty(rt, "nativeNodeHandle"), jsInvoker),
      bridging::fromJs<decltype(types.positionIndex)>(rt, value.getProperty(rt, "positionIndex"), jsInvoker),
      bridging::fromJs<decltype(types.coordinates)>(rt, value.getProperty(rt, "coordinates"), jsInvoker),
      bridging::fromJs<decltype(types.fragmentUuid)>(rt, value.getProperty(rt, "fragmentUuid"), jsInvoker),
      bridging::fromJs<decltype(types.segmentValues)>(rt, value.getProperty(rt, "segmentValues"), jsInvoker),
      bridging::fromJs<decltype(types.colorRampStops)>(rt, value.getProperty(rt, "colorRampStops"), jsInvoker),
      bridging::fromJs<decltype(types.blendRatio)>(rt, value.getProperty(rt, "blendRatio"), jsInvoker),
      bridging::fromJs<decltype(types.supportsGestures)>(rt, value.getProperty(rt, "supportsGestures"), jsInvoker),
      bridging::fromJs<decltype(types.style)>(rt, value.getProperty(rt, "style"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static int nativeNodeHandleToJs(jsi::Runtime &rt, decltype(types.nativeNodeHandle) value) {
    return bridging::toJs(rt, value);
  }
  static int positionIndexToJs(jsi::Runtime &rt, decltype(types.positionIndex) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array coordinatesToJs(jsi::Runtime &rt, decltype(types.coordinates) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String fragmentUuidToJs(jsi::Runtime &rt, decltype(types.fragmentUuid) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array segmentValuesToJs(jsi::Runtime &rt, decltype(types.segmentValues) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array colorRampStopsToJs(jsi::Runtime &rt, decltype(types.colorRampStops) value) {
    return bridging::toJs(rt, value);
  }
  static double blendRatioToJs(jsi::Runtime &rt, decltype(types.blendRatio) value) {
    return bridging::toJs(rt, value);
  }
  static bool supportsGesturesToJs(jsi::Runtime &rt, decltype(types.supportsGestures) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Object styleToJs(jsi::Runtime &rt, decltype(types.style) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    if (value.nativeNodeHandle) {
      result.setProperty(rt, "nativeNodeHandle", bridging::toJs(rt, value.nativeNodeHandle.value(), jsInvoker));
    }
    if (value.positionIndex) {
      result.setProperty(rt, "positionIndex", bridging::toJs(rt, value.positionIndex.value(), jsInvoker));
    }
    if (value.coordinates) {
      result.setProperty(rt, "coordinates", bridging::toJs(rt, value.coordinates.value(), jsInvoker));
    }
    if (value.fragmentUuid) {
      result.setProperty(rt, "fragmentUuid", bridging::toJs(rt, value.fragmentUuid.value(), jsInvoker));
    }
    if (value.segmentValues) {
      result.setProperty(rt, "segmentValues", bridging::toJs(rt, value.segmentValues.value(), jsInvoker));
    }
    if (value.colorRampStops) {
      result.setProperty(rt, "colorRampStops", bridging::toJs(rt, value.colorRampStops.value(), jsInvoker));
    }
    if (value.blendRatio) {
      result.setProperty(rt, "blendRatio", bridging::toJs(rt, value.blendRatio.value(), jsInvoker));
    }
    if (value.supportsGestures) {
      result.setProperty(rt, "supportsGestures", bridging::toJs(rt, value.supportsGestures.value(), jsInvoker));
    }
    if (value.style) {
      result.setProperty(rt, "style", bridging::toJs(rt, value.style.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeLayerPathColorRampGeometryStyle

template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6, typename P7, typename P8, typename P9, typename P10, typename P11, typename P12, typename P13, typename P14, typename P15, typename P16, typename P17>
struct NativeLayerPathColorRampGeometryStyle {
  P0 strokeWidth{};
  P1 strokeColor{};
  P2 fillColor{};
  P3 fillAlpha{};
  P4 buffer{};
  P5 scalingZoomLevel{};
  P6 cap{};
  P7 fixed{};
  P8 strokeIncrease{};
  P9 blur{};
  P10 stipple{};
  P11 stippleColor{};
  P12 stippleWidth{};
  P13 dropDistance{};
  P14 textureRepeat{};
  P15 heightOffset{};
  P16 randomOffset{};
  P17 transparent;
  bool operator==(const NativeLayerPathColorRampGeometryStyle &other) const {
    return strokeWidth == other.strokeWidth && strokeColor == other.strokeColor && fillColor == other.fillColor && fillAlpha == other.fillAlpha && buffer == other.buffer && scalingZoomLevel == other.scalingZoomLevel && cap == other.cap && fixed == other.fixed && strokeIncrease == other.strokeIncrease && blur == other.blur && stipple == other.stipple && stippleColor == other.stippleColor && stippleWidth == other.stippleWidth && dropDistance == other.dropDistance && textureRepeat == other.textureRepeat && heightOffset == other.heightOffset && randomOffset == other.randomOffset && transparent == other.transparent;
  }
};

template <typename T>
struct NativeLayerPathColorRampGeometryStyleBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.strokeWidth)>(rt, value.getProperty(rt, "strokeWidth"), jsInvoker),
      bridging::fromJs<decltype(types.strokeColor)>(rt, value.getProperty(rt, "strokeColor"), jsInvoker),
      bridging::fromJs<decltype(types.fillColor)>(rt, value.getProperty(rt, "fillColor"), jsInvoker),
      bridging::fromJs<decltype(types.fillAlpha)>(rt, value.getProperty(rt, "fillAlpha"), jsInvoker),
      bridging::fromJs<decltype(types.buffer)>(rt, value.getProperty(rt, "buffer"), jsInvoker),
      bridging::fromJs<decltype(types.scalingZoomLevel)>(rt, value.getProperty(rt, "scalingZoomLevel"), jsInvoker),
      bridging::fromJs<decltype(types.cap)>(rt, value.getProperty(rt, "cap"), jsInvoker),
      bridging::fromJs<decltype(types.fixed)>(rt, value.getProperty(rt, "fixed"), jsInvoker),
      bridging::fromJs<decltype(types.strokeIncrease)>(rt, value.getProperty(rt, "strokeIncrease"), jsInvoker),
      bridging::fromJs<decltype(types.blur)>(rt, value.getProperty(rt, "blur"), jsInvoker),
      bridging::fromJs<decltype(types.stipple)>(rt, value.getProperty(rt, "stipple"), jsInvoker),
      bridging::fromJs<decltype(types.stippleColor)>(rt, value.getProperty(rt, "stippleColor"), jsInvoker),
      bridging::fromJs<decltype(types.stippleWidth)>(rt, value.getProperty(rt, "stippleWidth"), jsInvoker),
      bridging::fromJs<decltype(types.dropDistance)>(rt, value.getProperty(rt, "dropDistance"), jsInvoker),
      bridging::fromJs<decltype(types.textureRepeat)>(rt, value.getProperty(rt, "textureRepeat"), jsInvoker),
      bridging::fromJs<decltype(types.heightOffset)>(rt, value.getProperty(rt, "heightOffset"), jsInvoker),
      bridging::fromJs<decltype(types.randomOffset)>(rt, value.getProperty(rt, "randomOffset"), jsInvoker),
      bridging::fromJs<decltype(types.transparent)>(rt, value.getProperty(rt, "transparent"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static double strokeWidthToJs(jsi::Runtime &rt, decltype(types.strokeWidth) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String strokeColorToJs(jsi::Runtime &rt, decltype(types.strokeColor) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String fillColorToJs(jsi::Runtime &rt, decltype(types.fillColor) value) {
    return bridging::toJs(rt, value);
  }
  static double fillAlphaToJs(jsi::Runtime &rt, decltype(types.fillAlpha) value) {
    return bridging::toJs(rt, value);
  }
  static double bufferToJs(jsi::Runtime &rt, decltype(types.buffer) value) {
    return bridging::toJs(rt, value);
  }
  static int scalingZoomLevelToJs(jsi::Runtime &rt, decltype(types.scalingZoomLevel) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String capToJs(jsi::Runtime &rt, decltype(types.cap) value) {
    return bridging::toJs(rt, value);
  }
  static bool fixedToJs(jsi::Runtime &rt, decltype(types.fixed) value) {
    return bridging::toJs(rt, value);
  }
  static double strokeIncreaseToJs(jsi::Runtime &rt, decltype(types.strokeIncrease) value) {
    return bridging::toJs(rt, value);
  }
  static double blurToJs(jsi::Runtime &rt, decltype(types.blur) value) {
    return bridging::toJs(rt, value);
  }
  static int stippleToJs(jsi::Runtime &rt, decltype(types.stipple) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String stippleColorToJs(jsi::Runtime &rt, decltype(types.stippleColor) value) {
    return bridging::toJs(rt, value);
  }
  static double stippleWidthToJs(jsi::Runtime &rt, decltype(types.stippleWidth) value) {
    return bridging::toJs(rt, value);
  }
  static double dropDistanceToJs(jsi::Runtime &rt, decltype(types.dropDistance) value) {
    return bridging::toJs(rt, value);
  }
  static bool textureRepeatToJs(jsi::Runtime &rt, decltype(types.textureRepeat) value) {
    return bridging::toJs(rt, value);
  }
  static double heightOffsetToJs(jsi::Runtime &rt, decltype(types.heightOffset) value) {
    return bridging::toJs(rt, value);
  }
  static bool randomOffsetToJs(jsi::Runtime &rt, decltype(types.randomOffset) value) {
    return bridging::toJs(rt, value);
  }
  static bool transparentToJs(jsi::Runtime &rt, decltype(types.transparent) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    if (value.strokeWidth) {
      result.setProperty(rt, "strokeWidth", bridging::toJs(rt, value.strokeWidth.value(), jsInvoker));
    }
    if (value.strokeColor) {
      result.setProperty(rt, "strokeColor", bridging::toJs(rt, value.strokeColor.value(), jsInvoker));
    }
    if (value.fillColor) {
      result.setProperty(rt, "fillColor", bridging::toJs(rt, value.fillColor.value(), jsInvoker));
    }
    if (value.fillAlpha) {
      result.setProperty(rt, "fillAlpha", bridging::toJs(rt, value.fillAlpha.value(), jsInvoker));
    }
    if (value.buffer) {
      result.setProperty(rt, "buffer", bridging::toJs(rt, value.buffer.value(), jsInvoker));
    }
    if (value.scalingZoomLevel) {
      result.setProperty(rt, "scalingZoomLevel", bridging::toJs(rt, value.scalingZoomLevel.value(), jsInvoker));
    }
    if (value.cap) {
      result.setProperty(rt, "cap", bridging::toJs(rt, value.cap.value(), jsInvoker));
    }
    if (value.fixed) {
      result.setProperty(rt, "fixed", bridging::toJs(rt, value.fixed.value(), jsInvoker));
    }
    if (value.strokeIncrease) {
      result.setProperty(rt, "strokeIncrease", bridging::toJs(rt, value.strokeIncrease.value(), jsInvoker));
    }
    if (value.blur) {
      result.setProperty(rt, "blur", bridging::toJs(rt, value.blur.value(), jsInvoker));
    }
    if (value.stipple) {
      result.setProperty(rt, "stipple", bridging::toJs(rt, value.stipple.value(), jsInvoker));
    }
    if (value.stippleColor) {
      result.setProperty(rt, "stippleColor", bridging::toJs(rt, value.stippleColor.value(), jsInvoker));
    }
    if (value.stippleWidth) {
      result.setProperty(rt, "stippleWidth", bridging::toJs(rt, value.stippleWidth.value(), jsInvoker));
    }
    if (value.dropDistance) {
      result.setProperty(rt, "dropDistance", bridging::toJs(rt, value.dropDistance.value(), jsInvoker));
    }
    if (value.textureRepeat) {
      result.setProperty(rt, "textureRepeat", bridging::toJs(rt, value.textureRepeat.value(), jsInvoker));
    }
    if (value.heightOffset) {
      result.setProperty(rt, "heightOffset", bridging::toJs(rt, value.heightOffset.value(), jsInvoker));
    }
    if (value.randomOffset) {
      result.setProperty(rt, "randomOffset", bridging::toJs(rt, value.randomOffset.value(), jsInvoker));
    }
    if (value.transparent) {
      result.setProperty(rt, "transparent", bridging::toJs(rt, value.transparent.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeLayerPathColorRampLayerPathColorRampResponse

template <typename P0, typename P1, typename P2>
struct NativeLayerPathColorRampLayerPathColorRampResponse {
  P0 uuid{};
  P1 nativeNodeHandle{};
  P2 coordinates;
  bool operator==(const NativeLayerPathColorRampLayerPathColorRampResponse &other) const {
    return uuid == other.uuid && nativeNodeHandle == other.nativeNodeHandle && coordinates == other.coordinates;
  }
};

template <typename T>
struct NativeLayerPathColorRampLayerPathColorRampResponseBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.uuid)>(rt, value.getProperty(rt, "uuid"), jsInvoker),
      bridging::fromJs<decltype(types.nativeNodeHandle)>(rt, value.getProperty(rt, "nativeNodeHandle"), jsInvoker),
      bridging::fromJs<decltype(types.coordinates)>(rt, value.getProperty(rt, "coordinates"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String uuidToJs(jsi::Runtime &rt, decltype(types.uuid) value) {
    return bridging::toJs(rt, value);
  }
  static int nativeNodeHandleToJs(jsi::Runtime &rt, decltype(types.nativeNodeHandle) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Array coordinatesToJs(jsi::Runtime &rt, decltype(types.coordinates) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "uuid", bridging::toJs(rt, value.uuid, jsInvoker));
    result.setProperty(rt, "nativeNodeHandle", bridging::toJs(rt, value.nativeNodeHandle, jsInvoker));
    if (value.coordinates) {
      result.setProperty(rt, "coordinates", bridging::toJs(rt, value.coordinates.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeLayerPathColorRampModuleParams

template <typename P0, typename P1, typename P2, typename P3>
struct NativeLayerPathColorRampModuleParams {
  P0 style{};
  P1 responseInclude{};
  P2 gestureScreenDistance{};
  P3 simplificationTolerance;
  bool operator==(const NativeLayerPathColorRampModuleParams &other) const {
    return style == other.style && responseInclude == other.responseInclude && gestureScreenDistance == other.gestureScreenDistance && simplificationTolerance == other.simplificationTolerance;
  }
};

template <typename T>
struct NativeLayerPathColorRampModuleParamsBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.style)>(rt, value.getProperty(rt, "style"), jsInvoker),
      bridging::fromJs<decltype(types.responseInclude)>(rt, value.getProperty(rt, "responseInclude"), jsInvoker),
      bridging::fromJs<decltype(types.gestureScreenDistance)>(rt, value.getProperty(rt, "gestureScreenDistance"), jsInvoker),
      bridging::fromJs<decltype(types.simplificationTolerance)>(rt, value.getProperty(rt, "simplificationTolerance"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::Object styleToJs(jsi::Runtime &rt, decltype(types.style) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Object responseIncludeToJs(jsi::Runtime &rt, decltype(types.responseInclude) value) {
    return bridging::toJs(rt, value);
  }
  static double gestureScreenDistanceToJs(jsi::Runtime &rt, decltype(types.gestureScreenDistance) value) {
    return bridging::toJs(rt, value);
  }
  static double simplificationToleranceToJs(jsi::Runtime &rt, decltype(types.simplificationTolerance) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    if (value.style) {
      result.setProperty(rt, "style", bridging::toJs(rt, value.style.value(), jsInvoker));
    }
    if (value.responseInclude) {
      result.setProperty(rt, "responseInclude", bridging::toJs(rt, value.responseInclude.value(), jsInvoker));
    }
    if (value.gestureScreenDistance) {
      result.setProperty(rt, "gestureScreenDistance", bridging::toJs(rt, value.gestureScreenDistance.value(), jsInvoker));
    }
    if (value.simplificationTolerance) {
      result.setProperty(rt, "simplificationTolerance", bridging::toJs(rt, value.simplificationTolerance.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeLayerPathColorRampRemoveLayerParams

template <typename P0, typename P1>
struct NativeLayerPathColorRampRemoveLayerParams {
  P0 nativeNodeHandle{};
  P1 uuid;
  bool operator==(const NativeLayerPathColorRampRemoveLayerParams &other) const {
    return nativeNodeHandle == other.nativeNodeHandle && uuid == other.uuid;
  }
};

template <typename T>
struct NativeLayerPathColorRampRemoveLayerParamsBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.nativeNodeHandle)>(rt, value.getProperty(rt, "nativeNodeHandle"), jsInvoker),
      bridging::fromJs<decltype(types.uuid)>(rt, value.getProperty(rt, "uuid"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static int nativeNodeHandleToJs(jsi::Runtime &rt, decltype(types.nativeNodeHandle) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String uuidToJs(jsi::Runtime &rt, decltype(types.uuid) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "nativeNodeHandle", bridging::toJs(rt, value.nativeNodeHandle, jsInvoker));
    result.setProperty(rt, "uuid", bridging::toJs(rt, value.uuid, jsInvoker));
    return result;
  }
};



#pragma mark - NativeLayerPathColorRampResponseBase

template <typename P0, typename P1>
struct NativeLayerPathColorRampResponseBase {
  P0 uuid{};
  P1 nativeNodeHandle;
  bool operator==(const NativeLayerPathColorRampResponseBase &other) const {
    return uuid == other.uuid && nativeNodeHandle == other.nativeNodeHandle;
  }
};

template <typename T>
struct NativeLayerPathColorRampResponseBaseBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.uuid)>(rt, value.getProperty(rt, "uuid"), jsInvoker),
      bridging::fromJs<decltype(types.nativeNodeHandle)>(rt, value.getProperty(rt, "nativeNodeHandle"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String uuidToJs(jsi::Runtime &rt, decltype(types.uuid) value) {
    return bridging::toJs(rt, value);
  }
  static int nativeNodeHandleToJs(jsi::Runtime &rt, decltype(types.nativeNodeHandle) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "uuid", bridging::toJs(rt, value.uuid, jsInvoker));
    result.setProperty(rt, "nativeNodeHandle", bridging::toJs(rt, value.nativeNodeHandle, jsInvoker));
    return result;
  }
};


template <typename T>
class JSI_EXPORT NativeLayerPathColorRampCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "LayerPathColorRamp";

protected:
  NativeLayerPathColorRampCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeLayerPathColorRampCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["getConstants"] = MethodMetadata {.argCount = 0, .invoker = __getConstants};
    methodMap_["createLayer"] = MethodMetadata {.argCount = 1, .invoker = __createLayer};
    methodMap_["removeLayer"] = MethodMetadata {.argCount = 1, .invoker = __removeLayer};
    methodMap_["addListener"] = MethodMetadata {.argCount = 1, .invoker = __addListener};
    methodMap_["removeListeners"] = MethodMetadata {.argCount = 1, .invoker = __removeListeners};
  }
  
private:
  static jsi::Value __getConstants(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getConstants) == 1,
      "Expected getConstants(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Object>(rt, &T::getConstants,  static_cast<NativeLayerPathColorRampCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __createLayer(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::createLayer) == 2,
      "Expected createLayer(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::createLayer,  static_cast<NativeLayerPathColorRampCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt));
  }

  static jsi::Value __removeLayer(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::removeLayer) == 2,
      "Expected removeLayer(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::removeLayer,  static_cast<NativeLayerPathColorRampCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt));
  }

  static jsi::Value __addListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::addListener) == 2,
      "Expected addListener(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::addListener,  static_cast<NativeLayerPathColorRampCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __removeListeners(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::removeListeners) == 2,
      "Expected removeListeners(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::removeListeners,  static_cast<NativeLayerPathColorRampCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());return jsi::Value::undefined();
  }
};

} // namespace facebook::react
